$(document).ready(function(){
    $('#send-questionnaire').mouseenter(function(){
      $('.img-feedback-2').hide();
      $('.img-feedback-1').show();
    });
    $('#feedback').mouseenter(function(){
      $('.img-feedback-1').hide();
      $('.img-feedback-2').show();
    });
});
